services:
  mariadb:
    image: mariadb:11
    container_name: itsconv-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: its_web
      MYSQL_USER: its_web
      MYSQL_PASSWORD: its_web
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
